// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Info describes the host the application is running on.
 */
export interface Info {
    "os": string;
    "version": string;
    "isAdmin": boolean;
    "arch": string;
}
