// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Candidate is a file or directory that matched a junk rule during a scan.
 */
export interface Candidate {
    "path": string;
    "name": string;
    "isDir": boolean;
    "category": Category;
    "size": number;
    "reason": string;
    "protected": boolean;
    "scanSource": string;
}

/**
 * Category is the structured classification of a junk candidate.
 */
export enum Category {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CategoryTempFiles = "temporary-files",
    CategoryCache = "cache",
    CategoryLogs = "logs",
    CategoryCrashDumps = "crash-dumps",
    CategoryBackups = "backups",
    CategoryPartialDownloads = "partial-downloads",
    CategoryBuildArtifacts = "build-artifacts",
    CategoryEditorTemp = "editor-temp",
    CategoryOtherJunk = "other-junk",
};

/**
 * Progress is the live state of an ongoing scan.
 */
export interface Progress {
    "scanId": string;
    "scannedFiles": number;
    "candidates": number;
    "errors": number;
    "currentPath": string;
    "done": boolean;
}

/**
 * ScanError records a path that could not be read during a scan.
 */
export interface ScanError {
    "path": string;
    "error": string;
}
