// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Candidate is a file or directory that matched a junk rule during a scan.
 */
export interface Candidate {
    "path": string;
    "name": string;
    "isDir": boolean;
    "category": Category;
    "size": number;
    "reason": string;
    "protected": boolean;
    "scanSource": string;
}

/**
 * Category is the structured classification of a junk candidate.
 */
export enum Category {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CategoryTempFiles = "temporary-files",
    CategoryCache = "cache",
    CategoryLogs = "logs",
    CategoryCrashDumps = "crash-dumps",
    CategoryBackups = "backups",
    CategoryPartialDownloads = "partial-downloads",
    CategoryBuildArtifacts = "build-artifacts",
    CategoryEditorTemp = "editor-temp",
    CategoryOtherJunk = "other-junk",
};

/**
 * DriveInfo describes one detected Windows logical drive. The frontend only
 * ever selects scan roots from this backend-provided list; it never invents
 * paths.
 */
export interface DriveInfo {
    /**
     * e.g. "C:\\"
     */
    "root": string;

    /**
     * volume label, may be empty
     */
    "label": string;

    /**
     * fixed | removable | network | optical | ram | unknown
     */
    "type": string;

    /**
     * 0 when the drive is not ready
     */
    "totalBytes": number;

    /**
     * 0 when the drive is not ready
     */
    "freeBytes": number;

    /**
     * false for empty optical drives etc.
     */
    "ready": boolean;
}

/**
 * Progress is the live state of an ongoing scan.
 */
export interface Progress {
    "scanId": string;
    "scannedFiles": number;
    "candidates": number;
    "errors": number;
    "currentPath": string;
    "done": boolean;
}

/**
 * ScanError records a path that could not be read during a scan.
 */
export interface ScanError {
    "path": string;
    "error": string;
}
