// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CleanupService handles deletion of scan candidates. It never accepts an
 * arbitrary path: every selection is validated against the scan session
 * snapshot by the cleaner (re-stat, protection, drive-root, reparse-point,
 * identity checks) before anything is removed.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as report$0 from "../internal/report/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cleanup validates and deletes the selected paths against a scan session.
 * dryRun performs the full validation without touching the filesystem.
 */
export function Cleanup(dryRun: boolean, scanID: string, selected: string[] | null): $CancellablePromise<report$0.Report> {
    return $Call.ByID(2615587543, dryRun, scanID, selected);
}

/**
 * GetLastReport returns the most recent cleanup report (history page).
 */
export function GetLastReport(): $CancellablePromise<$models.lastReportEntry | null> {
    return $Call.ByID(2441938141);
}
