// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RulesService exposes the whitelist (protection-only) engine. It is
 * distinct from the application updater: rules updates add protection, they
 * are never application binary updates.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetRulesStatus returns the current whitelist snapshot.
 */
export function GetRulesStatus(): $CancellablePromise<$models.RulesStatus> {
    return $Call.ByID(2262874091);
}

/**
 * RefreshRules forces a fresh remote whitelist check (bypassing the TTL)
 * and returns the updated snapshot. Any remote failure keeps the last valid
 * ruleset active and is reported in the status.
 */
export function RefreshRules(): $CancellablePromise<$models.RulesStatus> {
    return $Call.ByID(2690265164);
}

/**
 * SetAppVersion stores the build version for compatibility checks against
 * remote manifests. Called from main before the background check starts.
 */
export function SetAppVersion(v: string): $CancellablePromise<void> {
    return $Call.ByID(415059203, v);
}

/**
 * StartBackgroundCheck runs one non-blocking TTL-driven whitelist check in
 * the background. It never blocks application startup and failures are
 * quiet (the last valid ruleset stays active).
 */
export function StartBackgroundCheck(): $CancellablePromise<void> {
    return $Call.ByID(3671230050);
}
