// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ScannerService exposes scan control to the frontend. Scans run in a
 * goroutine and report progress through the "scan:progress" / "scan:done"
 * events so the UI never blocks.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as platform$0 from "../internal/platform/models.js";

/**
 * CancelScan stops an in-progress scan by id.
 */
export function CancelScan(scanID: string): $CancellablePromise<void> {
    return $Call.ByID(2954532496, scanID);
}

/**
 * GetCandidates returns the scan's candidates sorted by size (descending),
 * with directories first.
 */
export function GetCandidates(scanID: string): $CancellablePromise<model$0.Candidate[] | null> {
    return $Call.ByID(312517211, scanID);
}

/**
 * GetProtectedPaths returns the canonical protected roots (informational).
 */
export function GetProtectedPaths(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3656526215);
}

/**
 * GetScanErrors returns the per-path errors recorded during a scan.
 */
export function GetScanErrors(scanID: string): $CancellablePromise<model$0.ScanError[] | null> {
    return $Call.ByID(1658001527, scanID);
}

/**
 * GetScanState returns the current progress snapshot for a scan.
 */
export function GetScanState(scanID: string): $CancellablePromise<model$0.Progress> {
    return $Call.ByID(967770813, scanID);
}

/**
 * GetSystemInfo reports OS version and elevation status.
 */
export function GetSystemInfo(): $CancellablePromise<platform$0.Info> {
    return $Call.ByID(2852109104);
}

/**
 * ListDrives returns the currently available Windows drives (system/fixed
 * first). The frontend only ever selects scan roots from this list.
 */
export function ListDrives(): $CancellablePromise<model$0.DriveInfo[] | null> {
    return $Call.ByID(4172432574);
}

/**
 * StartScan launches an asynchronous scan and returns its scan id.
 */
export function StartScan(targets: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(2719489716, targets);
}
