// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService exposes settings and static app metadata.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAppInfo returns static application metadata, including the build-time
 * version (injected via -ldflags, same value the updater compares).
 */
export function GetAppInfo(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(1724818459);
}

/**
 * GetSettings returns the current settings snapshot.
 */
export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(3193827985);
}

/**
 * RelaunchElevated requests an elevated relaunch of Junk-Fuck. Elevation is
 * always an explicit user action: this triggers the Windows UAC prompt and
 * never runs silently.
 * 
 * On success (UAC accepted) the current instance cancels any active scan
 * and quits shortly after, so only the elevated instance keeps running —
 * two long-lived instances are never created. On cancel or failure the
 * current instance stays open and keeps working.
 */
export function RelaunchElevated(): $CancellablePromise<boolean> {
    return $Call.ByID(3102818888);
}

/**
 * SaveSettings validates and stores a settings snapshot.
 */
export function SaveSettings(settings: $models.Settings): $CancellablePromise<$models.Settings> {
    return $Call.ByID(2049705744, settings);
}

/**
 * SetVersion stores the build-time version for GetAppInfo and the updater.
 */
export function SetVersion(v: string): $CancellablePromise<void> {
    return $Call.ByID(918327788, v);
}
