// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService drives the official Wails v3 updater. Update installation is
 * refused while a scan or cleanup is in progress (installation restarts the
 * app, which must never interrupt filesystem work).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "../../../wailsapp/wails/v3/pkg/updater/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdates runs a manual update check. It never installs.
 */
export function CheckForUpdates(): $CancellablePromise<$models.UpdateState> {
    return $Call.ByID(3449933179);
}

/**
 * GetUpdateState returns the current updater snapshot.
 */
export function GetUpdateState(): $CancellablePromise<$models.UpdateState> {
    return $Call.ByID(4136184330);
}

/**
 * InstallUpdate downloads, verifies and installs the available update.
 * Refused while a scan or cleanup is running.
 */
export function InstallUpdate(): $CancellablePromise<$models.UpdateState> {
    return $Call.ByID(822046230);
}

/**
 * SetUpdater wires the app's official updater instance (called from main).
 */
export function SetUpdater(u: updater$0.Updater | null): $CancellablePromise<void> {
    return $Call.ByID(2923472229, u);
}
