// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Item is the result of one candidate during cleanup.
 */
export interface Item {
    "path": string;
    "name": string;
    "status": Status;
    "reason": string;
}

/**
 * Report summarizes a cleanup operation.
 */
export interface Report {
    "dryRun": boolean;
    "deletedCount": number;
    "skippedCount": number;
    "failedCount": number;
    "bytesFreed": number;
    "items": Item[] | null;
}

/**
 * Status describes the outcome of a single cleanup item.
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusDeleted = "deleted",
    StatusSkipped = "skipped",
    StatusFailed = "failed",
};
