// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelScan(arg1) {
  return window['go']['main']['App']['CancelScan'](arg1);
}

export function Cleanup(arg1, arg2, arg3) {
  return window['go']['main']['App']['Cleanup'](arg1, arg2, arg3);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetCandidates(arg1) {
  return window['go']['main']['App']['GetCandidates'](arg1);
}

export function GetLastReport() {
  return window['go']['main']['App']['GetLastReport']();
}

export function GetProtectedPaths() {
  return window['go']['main']['App']['GetProtectedPaths']();
}

export function GetScanErrors(arg1) {
  return window['go']['main']['App']['GetScanErrors'](arg1);
}

export function GetScanState(arg1) {
  return window['go']['main']['App']['GetScanState'](arg1);
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}
