// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {report} from '../models';
import {model} from '../models';
import {main} from '../models';
import {platform} from '../models';

export function CancelScan(arg1:string):Promise<void>;

export function Cleanup(arg1:boolean,arg2:string,arg3:Array<string>):Promise<report.Report>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetCandidates(arg1:string):Promise<Array<model.Candidate>>;

export function GetLastReport():Promise<main.lastReportEntry>;

export function GetProtectedPaths():Promise<Array<string>>;

export function GetScanErrors(arg1:string):Promise<Array<model.ScanError>>;

export function GetScanState(arg1:string):Promise<model.Progress>;

export function GetSystemInfo():Promise<platform.Info>;

export function StartScan(arg1:Array<string>):Promise<string>;
